import React, { useState } from 'react';
import { X, Code2, Copy, Check, Terminal, ShieldCheck, Zap } from 'lucide-react';

interface TechSpecModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const TechSpecModal: React.FC<TechSpecModalProps> = ({ isOpen, onClose }) => {
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  if (!isOpen) return null;

  const baseUrl = typeof window !== 'undefined' ? window.location.origin : 'http://localhost:3000';

  const curlExamples = [
    {
      title: "1. Get 31-Day Cohort Curriculum",
      method: "GET",
      endpoint: "/api/v1/curriculum",
      command: `curl -X GET "${baseUrl}/api/v1/curriculum"`
    },
    {
      title: "2. Get Candidate Profiles",
      method: "GET",
      endpoint: "/api/v1/candidates",
      command: `curl -X GET "${baseUrl}/api/v1/candidates"`
    },
    {
      title: "3. Start Personalized Interview",
      method: "POST",
      endpoint: "/api/v1/interview/start",
      command: `curl -X POST "${baseUrl}/api/v1/interview/start" \\
  -H "Content-Type: application/json" \\
  -d '{"candidate_id": "sana-khan", "num_questions": 8}'`
    },
    {
      title: "4. Submit Answer & Get Adaptive Next Question",
      method: "POST",
      endpoint: "/api/v1/interview/answer",
      command: `curl -X POST "${baseUrl}/api/v1/interview/answer" \\
  -H "Content-Type: application/json" \\
  -d '{"interview_id": "<YOUR_SESSION_ID>", "answer": "Self-attention computes Query, Key, Value attention scores..."}'`
    },
    {
      title: "5. Retrieve Final Report",
      method: "GET",
      endpoint: "/api/v1/interview/:id/report",
      command: `curl -X GET "${baseUrl}/api/v1/interview/<YOUR_SESSION_ID>/report"`
    }
  ];

  const handleCopy = (command: string, index: number) => {
    navigator.clipboard.writeText(command);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-fade-in">
      <div className="dark:bg-[#030712]/95 bg-white border dark:border-white/10 border-slate-200 rounded-2xl max-w-3xl w-full max-h-[85vh] overflow-y-auto shadow-2xl flex flex-col backdrop-blur-xl">
        {/* Modal Header */}
        <div className="sticky top-0 z-10 dark:bg-[#030712]/95 bg-white backdrop-blur-xl border-b dark:border-white/10 border-slate-200 p-5 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-xl bg-blue-500/20 border border-blue-500/30 text-blue-500 dark:text-blue-300">
              <Code2 className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold dark:text-white text-slate-900">Technical Specification & API Contract</h2>
              <p className="text-xs dark:text-slate-400 text-slate-600">RESTful HTTP Specification for Hackathon Evaluation</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-xl dark:hover:bg-white/10 hover:bg-slate-100 dark:text-slate-400 text-slate-500 hover:dark:text-white hover:text-slate-900 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Content */}
        <div className="p-6 space-y-6 text-xs dark:text-slate-300 text-slate-700 font-sans">
          {/* Minimum Requirements Compliance checklist */}
          <div className="p-4 rounded-xl bg-blue-500/10 border border-blue-500/20 space-y-2">
            <h3 className="font-bold text-blue-600 dark:text-blue-300 flex items-center gap-1.5 text-xs uppercase tracking-wider">
              <ShieldCheck className="w-4 h-4 text-blue-500 dark:text-blue-400" />
              Minimum Requirements Compliance Checklist
            </h3>
            <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-[11px] font-semibold dark:text-slate-200 text-slate-800">
              <li className="flex items-center gap-1.5">
                <Check className="w-3.5 h-3.5 text-emerald-500 dark:text-emerald-400" />
                <span>Conversational multi-turn technical interview</span>
              </li>
              <li className="flex items-center gap-1.5">
                <Check className="w-3.5 h-3.5 text-emerald-500 dark:text-emerald-400" />
                <span>Minimum 8 questions covering 4+ curriculum days</span>
              </li>
              <li className="flex items-center gap-1.5">
                <Check className="w-3.5 h-3.5 text-emerald-500 dark:text-emerald-400" />
                <span>Adaptive follow-up questions generated by Gemini AI</span>
              </li>
              <li className="flex items-center gap-1.5">
                <Check className="w-3.5 h-3.5 text-emerald-500 dark:text-emerald-400" />
                <span>Structured final feedback report & score breakdowns</span>
              </li>
              <li className="flex items-center gap-1.5 col-span-1 sm:col-span-2">
                <Check className="w-3.5 h-3.5 text-emerald-500 dark:text-emerald-400" />
                <span>Required HTTP REST endpoints exposed at /api/v1/*</span>
              </li>
            </ul>
          </div>

          {/* Endpoints & Curl Examples */}
          <div className="space-y-4">
            <h3 className="font-bold dark:text-white text-slate-900 text-sm">Interactive API Endpoints & cURL Commands</h3>

            {curlExamples.map((item, idx) => (
              <div key={idx} className="p-3.5 rounded-xl dark:bg-white/5 bg-slate-50 border dark:border-white/10 border-slate-200 backdrop-blur-md space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                      item.method === 'GET' ? 'bg-emerald-500/20 border border-emerald-500/30 text-emerald-600 dark:text-emerald-300' :
                      'bg-blue-500/20 border border-blue-500/30 text-blue-600 dark:text-blue-300'
                    }`}>
                      {item.method}
                    </span>
                    <span className="font-mono text-xs font-bold dark:text-white text-slate-900">{item.endpoint}</span>
                  </div>
                  <button
                    onClick={() => handleCopy(item.command, idx)}
                    className="p-1.5 rounded-lg dark:bg-white/10 bg-slate-200/80 border dark:border-white/10 border-slate-300 hover:text-blue-600 dark:hover:text-blue-300 transition-colors flex items-center gap-1 text-[10px] cursor-pointer"
                  >
                    {copiedIndex === idx ? (
                      <>
                        <Check className="w-3 h-3 text-emerald-500 dark:text-emerald-400" />
                        <span className="text-emerald-500 dark:text-emerald-400 font-bold">Copied!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3 h-3" />
                        <span>Copy cURL</span>
                      </>
                    )}
                  </button>
                </div>

                <pre className="p-2.5 rounded-lg dark:bg-[#030712] bg-slate-900 border dark:border-white/10 border-slate-800 text-blue-300 font-mono text-[11px] overflow-x-auto">
                  {item.command}
                </pre>
              </div>
            ))}
          </div>
        </div>

        {/* Modal Footer */}
        <div className="sticky bottom-0 z-10 dark:bg-[#030712]/95 bg-white backdrop-blur-xl border-t dark:border-white/10 border-slate-200 p-4 flex items-center justify-end gap-3">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 rounded-xl dark:bg-white/10 bg-slate-200 text-slate-700 dark:text-slate-300 font-bold text-xs hover:bg-slate-300 dark:hover:bg-white/20 transition-all cursor-pointer"
          >
            Close / Cancel
          </button>
        </div>
      </div>
    </div>
  );
};
